### **Importing Required Libaries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import opendatasets as od

### **Downloading Data**

In [2]:
url="https://www.kaggle.com/datasets/itsmesunil/bank-loan-modelling"
od.download(url)

Skipping, found downloaded files in ".\bank-loan-modelling" (use force=True to force download)


### **Importing Data**

In [3]:
data_description=pd.read_excel("bank-loan-modelling/Bank_Personal_Loan_Modelling.xlsx",sheet_name='Description',header=None)

In [4]:
data_description.iloc[7:,1:]

1                                                  2
7                   ID                                        Customer ID
8                  Age                  Customer's age in completed years
9           Experience                  #years of professional experience
10              Income               Annual income of the customer ($000)
11             ZIPCode                             Home Address ZIP code.
12              Family                        Family size of the customer
13               CCAvg     Avg. spending on credit cards per month ($000)
14           Education  Education Level. 1: Undergrad; 2: Graduate; 3:...
15            Mortgage             Value of house mortgage if any. ($000)
16       Personal Loan  Did this customer accept the personal loan off...
17  Securities Account  Does the customer have a securities account wi...
18          CD Account  Does the customer have a certificate of deposi...
19              Online  Does the customer use internet banking facilit...
20          CreditCard  Does the customer use a credit card issued by ...

In [5]:
df1=pd.read_excel("bank-loan-modelling/Bank_Personal_Loan_Modelling.xlsx",sheet_name='Data',index_col='ID')

In [6]:
df1.head(14)

Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
ID                                                                          
1    25           1      49     91107       4    1.6          1         0   
2    45          19      34     90089       3    1.5          1         0   
3    39          15      11     94720       1    1.0          1         0   
4    35           9     100     94112       1    2.7          2         0   
5    35           8      45     91330       4    1.0          2         0   
6    37          13      29     92121       4    0.4          2       155   
7    53          27      72     91711       2    1.5          2         0   
8    50          24      22     93943       1    0.3          3         0   
9    35          10      81     90089       3    0.6          2       104   
10   34           9     180     93023       1    8.9          3         0   
11   65          39     105     94710       4    2.4          3         0   
12   29           5      45     90277       3    0.1          2         0   
13   48          23     114     93106       2    3.8          3         0   
14   59          32      40     94920       4    2.5          2         0   

    Personal Loan  Securities Account  CD Account  Online  CreditCard  
ID                                                                     
1               0                   1           0       0           0  
2               0                   1           0       0           0  
3               0                   0           0       0           0  
4               0                   0           0       0           0  
5               0                   0           0       0           1  
6               0                   0           0       1           0  
7               0                   0           0       1           0  
8               0                   0           0       0           1  
9               0                   0           0       1           0  
10              1                   0           0       0           0  
11              0                   0           0       0           0  
12              0                   0           0       1           0  
13              0                   1           0       0           0  
14              0                   0           0       1           0

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 1 to 5000
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 5000 non-null   int64  
 1   Experience          5000 non-null   int64  
 2   Income              5000 non-null   int64  
 3   ZIP Code            5000 non-null   int64  
 4   Family              5000 non-null   int64  
 5   CCAvg               5000 non-null   float64
 6   Education           5000 non-null   int64  
 7   Mortgage            5000 non-null   int64  
 8   Personal Loan       5000 non-null   int64  
 9   Securities Account  5000 non-null   int64  
 10  CD Account          5000 non-null   int64  
 11  Online              5000 non-null   int64  
 12  CreditCard          5000 non-null   int64  
dtypes: float64(1), int64(12)
memory usage: 546.9 KB


In [8]:
df1.describe()

Age   Experience       Income      ZIP Code       Family  \
count  5000.000000  5000.000000  5000.000000   5000.000000  5000.000000   
mean     45.338400    20.104600    73.774200  93152.503000     2.396400   
std      11.463166    11.467954    46.033729   2121.852197     1.147663   
min      23.000000    -3.000000     8.000000   9307.000000     1.000000   
25%      35.000000    10.000000    39.000000  91911.000000     1.000000   
50%      45.000000    20.000000    64.000000  93437.000000     2.000000   
75%      55.000000    30.000000    98.000000  94608.000000     3.000000   
max      67.000000    43.000000   224.000000  96651.000000     4.000000   

             CCAvg    Education     Mortgage  Personal Loan  \
count  5000.000000  5000.000000  5000.000000    5000.000000   
mean      1.937913     1.881000    56.498800       0.096000   
std       1.747666     0.839869   101.713802       0.294621   
min       0.000000     1.000000     0.000000       0.000000   
25%       0.700000     1.000000     0.000000       0.000000   
50%       1.500000     2.000000     0.000000       0.000000   
75%       2.500000     3.000000   101.000000       0.000000   
max      10.000000     3.000000   635.000000       1.000000   

       Securities Account  CD Account       Online   CreditCard  
count         5000.000000  5000.00000  5000.000000  5000.000000  
mean             0.104400     0.06040     0.596800     0.294000  
std              0.305809     0.23825     0.490589     0.455637  
min              0.000000     0.00000     0.000000     0.000000  
25%              0.000000     0.00000     0.000000     0.000000  
50%              0.000000     0.00000     1.000000     0.000000  
75%              0.000000     0.00000     1.000000     1.000000  
max              1.000000     1.00000     1.000000     1.000000

In [9]:
df1.isna().sum()

Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [10]:
df1['Personal Loan'].unique()

array([0, 1], dtype=int64)

In [11]:
df1[['Personal Loan']].groupby(by=df1['Personal Loan']).count()

Personal Loan
Personal Loan               
0                       4520
1                        480

In [12]:
px.bar(df1, x=df1['Personal Loan'].value_counts().index, y=df1['Personal Loan'].value_counts().values, labels={'x':'Value', 'y':'Count'})

In [13]:
df1.Age.min()

23

In [14]:
df1.Age.max()

67

In [15]:
px.histogram(df1['Age'],nbins=50)

In [16]:
df1['Experience'].max()

43

In [17]:
df1['Experience'].min()

-3

In [18]:
df1[(df1['Experience']<0) & (df1['Personal Loan']==0)].shape

(52, 13)

We can see many rows have problem in data may be wrong data is inserted. <br>
If we check how many wrong data points have 1 that is they took personal loan during last campaign we will get 0 . that means these datapoints are not good for our model building.


In [19]:
df2=df1[(df1['Experience']>=0)]

In [20]:
df2.shape

(4948, 13)

In [21]:
px.histogram(df2['Experience'])

In [22]:
df2['Income'].min()

8

In [23]:
df2['Income'].max()

224

In [24]:
px.histogram(df2['Income'])

In [25]:
df2['Family'].min()

1

In [26]:
df2['Family'].max()

4

In [27]:
px.histogram(df2['Family'])

In [62]:
df2.columns

Index(['Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [69]:
df2[(df2['Personal Loan']==1) & (df2['CreditCard']==0)]

Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
ID                                                                            
10     34           9     180     93023       1    8.9          3         0   
17     38          14     130     95010       4    4.7          3       134   
19     46          21     193     91604       2    8.1          3         0   
39     42          18     141     94114       3    5.0          3         0   
43     32           7     132     90019       4    1.1          2       412   
...   ...         ...     ...       ...     ...    ...        ...       ...   
4843   49          23     174     95449       3    4.6          2       590   
4847   35          10     135     94596       3    4.8          2         0   
4860   34           8     165     91107       1    7.0          3       541   
4877   44          19     142     95054       1    1.5          3         0   
4942   28           4     112     90049       2    1.6          2         0   

      Personal Loan  Securities Account  CD Account  Online  CreditCard  
ID                                                                       
10                1                   0           0       0           0  
17                1                   0           0       0           0  
19                1                   0           0       0           0  
39                1                   1           1       1           0  
43                1                   0           0       1           0  
...             ...                 ...         ...     ...         ...  
4843              1                   0           0       0           0  
4847              1                   0           0       1           0  
4860              1                   0           0       0           0  
4877              1                   0           0       0           0  
4942              1                   0           0       1           0  

[337 rows x 13 columns]

In [30]:
df2['CCAvg'].max()

10.0

In [31]:
df2['CCAvg'].min()

0.0

In [35]:
px.histogram(df2['CCAvg'])

In [37]:
df2['Education'].unique()

array([1, 2, 3], dtype=int64)

In [39]:
px.histogram(df2['Education'])

In [48]:
df2['Mortgage'].min()

0

In [49]:
df2['Mortgage'].max()

635

In [53]:
df2['Securities Account'].unique()

array([1, 0], dtype=int64)

In [54]:
df2['Securities Account'].unique()

array([1, 0], dtype=int64)

In [55]:
df2['CD Account'].unique()

array([0, 1], dtype=int64)

In [56]:
df2['Online'].unique()

array([0, 1], dtype=int64)

In [58]:
df2['CreditCard'].unique()

array([0, 1], dtype=int64)

In [72]:
df2.columns.to_list()

['Age',
 'Experience',
 'Income',
 'ZIP Code',
 'Family',
 'CCAvg',
 'Education',
 'Mortgage',
 'Personal Loan',
 'Securities Account',
 'CD Account',
 'Online',
 'CreditCard']

### Splitting data for Training and Testing.

In [73]:
X=df2[['Age',
 'Experience',
 'Income',
 'Family',
 'CCAvg',
 'Education',
 'Mortgage',
 'Securities Account',
 'CD Account',
 'Online',
 'CreditCard']]

y=df2['Personal Loan']

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

### Model 

In [85]:
from sklearn.tree import DecisionTreeClassifier
Tree_Model=DecisionTreeClassifier()

In [86]:
Tree_Model.fit(X_train,y_train)

DecisionTreeClassifier()

In [87]:
y_pred=Tree_Model.predict(X_test)

In [88]:
from sklearn.metrics import accuracy_score

In [89]:
accuracy_score(y_test,y_pred)

0.9848484848484849

In [98]:
from sklearn.ensemble  import RandomForestClassifier
Rf_Classifier=RandomForestClassifier(n_estimators=20)

In [99]:
Rf_Classifier.fit(X_train,y_train)

RandomForestClassifier(n_estimators=20)

In [100]:
y_test1=Rf_Classifier.predict(X_test)

In [101]:
accuracy_score(y_test,y_test1)

0.9838383838383838